### ISSUE TITLE
shadcn suggestions prioritized over built-in emmet suggestions for e.g. 'div'

### ISSUE THREAD

**Issue by olemarius** [selemondev/vscode-shadcn-vue#17]
**Describe the bug**
When writing 'div' and hitting tab, I'm not getting tab but the alert snippet. Is there some way to put the suggstions after the built in emmet code completions ?

**To Reproduce**
1. Type div and hit tab

**Expected behavior**
Getting <div></div>

**Screenshots**
![image](https://github.com/selemondev/vscode-shadcn-vue/assets/184536/18e70cba-9543-443e-8c95-8e6e902511e3)

**Additional context**

**Comment by selemondev** [comment]
Thanks @olemarius for opening this issue. I have re-created the issue but everything is fine on my end.

Here are the screenshots:

<img width="1280" alt="Screenshot 2023-11-21 at 21 09 11" src="https://github.com/selemondev/vscode-shadcn-vue/assets/106826371/5edcbaf4-f807-4372-a754-2bd5237fcea4">
<img width="1280" alt="Screenshot 2023-11-21 at 21 09 16" src="https://github.com/selemondev/vscode-shadcn-vue/assets/106826371/e51be667-90d7-4adb-95fb-d53d7f7d48b9">

**Comment by olemarius** [comment]
Sorry, my bad! After looking at the code it didn't make sense that this should be different between our environments, so I did some digging and found that it's a vscode setting that I didn't know about 😅 

`"editor.snippetSuggestions": "top",`

Removing this resolves the issue
